const data = {
    urls: {
        it: "http://it.pnhbd.com",
        consultancy: "http://school.pnhdns.com",
        study: "http://morsuraha.com",
        shop: "http://easysalebd.com"
    },
    social: {
        facebook: "http://facebook.com/pnhitsolution",
        messenger: "http://m.me/pnhbd",
        whatsapp: "http://wa.me/8801873003333",
        instagram: "#",
        linkedin: "#",
        youtube: "#",
        twitter: "#"
    },
    settings: {
        email: "info@pnhbd.com",
        emailLink: "mailto:info@pnhbd.com",
        email2: "pnhbd123@gmail.com",
        emailLink2: "mailto:pnhbd123@gmail.com",
        mobile: "(+880)1873-003333",
        mobileLink: "tel:+88018730033",
        address: "184, Razia Plaza, Senpara Parbata. Mirpur-10, Dhaka-1216, Bangladesh",
        addressLink: "https://goo.gl/maps/LdDr4qzWZrYthNcj9"
    },
    portfolios: [
        {
            id: 1,
            title: "Alifa Landmark",
            description: "One of the best Manpower Recruiting agencies in Bangladesh, known for its professional and excellent services.",
            image: "/alifa-land.jpg",
            url: "https://alifagroup.com/landmark/",
        },
        {
            id: 2,
            title: "Alifa Overseas",
            description: "One of the industrys pioneers in Bangladesh real estate and housing sectors",
            image: "/alifa-overseas.jpg",
            url: "https://alifagroup.com/overseas/",
        },
        {
            id: 3,
            title: "Uddokta Group",
            description: "Best possible services and products to customers for attaining their full satisfaction",
            image: "/uddokta.jpg",
            url: "http://uddoktagroupbd.com/",
        },
        {
            id: 4,
            title: "Sames Pvt. Ltd.",
            description: "A global corporation that provides engineering, management consulting and project management solutions.",
            image: "/sames.jpg",
            url: "https://samespvtltd.com/",
        },
        {
            id: 5,
            title: "Mohammodia F&H Ltd.",
            description: "A Popular housing comapany located at Noakhali, Bangladesh",
            image: "/mohammadai.jpg",
            url: "https://mfhbd.com/",
        },
        {
            id: 6,
            title: "Eco Consultancy",
            description: "Eco Consultancy fills in as an extension between worldwide universities and Bangladeshi students",
            image: "/eco.jpg",
            url: "https://ecoconsultancybd.com/",
        },
        {
            id: 7,
            title: "Feather BD",
            description: "Reliable fashion E-commerce website",
            image: "/fether.jpg",
            url: "https://www.featherbd.com/",
        },
        {
            id: 8,
            title: "Master & Sons Ltd.",
            description: "Constuction coompany in Bangladesh. The optimal solution for your pre-engineered buildings & steel structure projects!",
            image: "/ms.jpg",
            url: "https://masterandsonsltd.com/",
        },
        {
            id: 9,
            title: "Metro Publications",
            description: "Metro publication is one of the renowned book publication houses in Bangladesh",
            image: "/metro.jpg",
            url: "https://metropublicationbd.com/",
        },
        {
            id: 10,
            title: "Motion Publications",
            description: "Motion publication is one of the renowned book publication houses in Bangladesh",
            image: "/motion.jpg",
            url: "https://motionp.com/",
        },
        {
            id: 11,
            title: "Sadaka Foundation",
            description: "One of the most non Profit charity organisation in Bangladesh who helps poor persons",
            image: "/sadaka.jpg",
            url: "https://www.sadakafoundation.org/",
        },
        {
            id: 12,
            title: "Best Up BD",
            description: "A Gaget seller Ecommerce website, located at Dhaka, Bangladesh",
            image: "bestup.jpg",
            url: "https://best-upbd.com/",
        },
        {
            id: 13,
            title: "DCS BD",
            description: "A popular E-commerce website, provide luxury & comfortable dresses",
            image: "/dcs.jpg",
            url: "https://www.dcsbd.com/",
        },
        {
            id: 14,
            title: "Musica Academy",
            description: "Piano learning website assist to learn one to one or on a gruop",
            image: "/musica.jpg",
            url: "https://musica-academy.com/",
        },
        {
            id: 15,
            title: "NLexic",
            description: "Europian export import comapany, export Mens fashion items, scrab etc.",
            image: "/nlexic.jpg",
            url: "https://nlexic.com/",
        },
        {
            id: 16,
            title: "Samir Group",
            description: "Multi product and service group of company",
            image: "/samir.jpg",
            url: "https://samirgroupbd.com/",
        },
        {
            id: 17,
            title: "Shadow Hoddings Ltd.",
            description: "very well known real estate company",
            image: "/shadow.jpg",
            url: "https://shadowholdingsltd.com/",
        },
    ]
}
export default data;